AETHERC ?= $(HOME)/scm/aether/build/aetherc

GENERATED := urls_generated.c parse_generated.c

all: $(GENERATED)

urls_generated.c: urls.ae
	$(AETHERC) --emit=lib $< $@

parse_generated.c: parse.ae
	$(AETHERC) --emit=lib $< $@

.PHONY: all
